### ISSUE TITLE
Does not work on beta.workflowy.com

### ISSUE THREAD

**Issue by xlloyd** [paulo1er/WorkFlowy-Presenter#17]
Excellent plugin! Unfortunately it does not render any markdown on beta.workflowy.com.

**Comment by paulo1er** [comment]
Ok, it's work now on beta.workflowy.com. You can update your extension to the version 2.3.1
But I don't test if all functionality work because I don't want to support the beta version.

**Comment by professor-eggs** [comment]
I understand. Thanks for the super quick response
